### Local Configuration Variables ###
HS_PATH: /home/hydro/hydroshare
HOST_SSL_DIR: /opt/hs-certs
HS_DATABASE: pg.deploy.sql
HS_LOG_FILES: /home/hydro/hydroshare/log
HS_SERVICE_UID: 20028
HS_SERVICE_GID: 10000

### Deployment Options ###
USE_NGINX: true
USE_SSL: true
USE_SECURITY: false
USE_HTTP_AUTH: false

### SSL Configuration Variables ###
SSL_CERT_DIR: /opt/hs-certs
SSL_CERT_FILE: SSL.crt
SSL_KEY_FILE: server.key

### nginx Configuration Variables ###
FQDN_OR_IP: cuahsi-dev-1.hydroshare.org
NGINX_DIR: /home/hydro/hydroshare/nginx

### Mount point in host operating system (outside docker)
### This is mounted from here into the Nginx container
IRODS_LOCAL_MOUNT: /irods

#### Mount points inside docker Nginx container
#### These give Nginx direct access to iRODS vaults
#### All ROOTs must be children of DOCKER_MAP ###
IRODS_DOCKER_MAP: /irods
IRODS_DATA_ROOT: /irods/hydroshare/vaults/cuahsi/irods1/home/cuahsi1DataProxy/
IRODS_USER_ROOT: /irods/hydroshare/vaults/cuahsi/irods2/home/cuahsi1UserProxy/
IRODS_CACHE_ROOT: /irods/hydroshare_vault/nginx_tmp/cuahsi-dev-1/cache/

#### Nginx worker process must be able to read iRODS files.
SENDFILE_IRODS_USER: irods
SENDFILE_IRODS_GROUP: irods
SENDFILE_IRODS_USER_ID: 20022
SENDFILE_IRODS_GROUP_ID: 10000

#### URIs in Nginx that activate reverse proxy service
#### These must agree with URIs in local_settings.py
IRODS_DATA_URI: irods-data
IRODS_USER_URI: irods-user
IRODS_CACHE_URI: irods-cache

# sets the concurrency of the celery worker
CELERY_CONCURRENCY: 4

### REQUIRES BLANK LINE AFTER LAST VARIABLE DEFINITION ###

